postgres:
  host: 127.0.0.1
  port: 5672
  username: admin
  password: admin
  db_name: postgres

redis:
  host: 127.0.0.1
  port: 6379

rabbitmq:
  username: guest
  password: guest
  host: 127.0.0.1
  port: 5672

server:
  port: 6666
